/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Search.java
 *
 * Created on 12 31, 18, 2:44:37 PM
 */
package payrollsystem;

/**
 *
 * @author user 2
 */
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Toolkit;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.util.logging.Level;
import java.util.logging.Logger;
public final class Search extends javax.swing.JFrame {
Connection myconObj = null; 
    Statement mystatObj = null;
    ResultSet myresObj = null;
    PreparedStatement mystateObj = null;
    int mousepX;
    int mousepY;
   
     public void selectLogin(){
    try{
    myconObj = DriverManager.getConnection("jdbc:derby://localhost:1527/Payrol", "tian", "tian");
    mystatObj = myconObj.createStatement();
    myresObj = mystatObj.executeQuery("select * from APP.CASHC");
    } 
    catch (SQLException e){
        JOptionPane.showMessageDialog(null, e);
    }
}
    
    public Search() {
        initComponents();
        Dates();
        setIcon();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField16 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        lblc = new javax.swing.JLabel();
        lblc1 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1221, 751));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(255, 0, 0));
        jPanel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel34.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("X");
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel34, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 0, 30, 30));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Job Ref", "FirstName", "Surname", "Address", "Phone NO", "Hour Work", "Basic Pay", "Payroll NO", "Overtime Rate", "National IN", "Student loan", "Tax", "Gross pay", "Net pay"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 920, 270));

        jPanel5.setBackground(new java.awt.Color(0, 37, 37));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 37, 37));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "SEARCH", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Footlight MT Light", 0, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField16.setBackground(new java.awt.Color(0, 51, 51));
        jTextField16.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jTextField16.setForeground(new java.awt.Color(255, 255, 255));
        jTextField16.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField16.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField16MouseClicked(evt);
            }
        });
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jTextField16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField16KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField16KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField16KeyTyped(evt);
            }
        });
        jPanel2.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 180, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Firstname");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Name :");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("ID :");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jTextField20.setBackground(new java.awt.Color(0, 51, 51));
        jTextField20.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jTextField20.setForeground(new java.awt.Color(255, 255, 255));
        jTextField20.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField20.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField20MouseClicked(evt);
            }
        });
        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        jTextField20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField20KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField20KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField20KeyTyped(evt);
            }
        });
        jPanel2.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 180, 30));
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 60, 40));
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 40, 40));

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 300, 220));

        jButton2.setBackground(new java.awt.Color(0, 37, 37));
        jButton2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Clear");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/remove.png"))); // NOI18N
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 80, 100));

        jButton3.setBackground(new java.awt.Color(0, 37, 37));
        jButton3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/rubbish.png"))); // NOI18N
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, 100));

        jButton4.setBackground(new java.awt.Color(0, 37, 37));
        jButton4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Print");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/printer.png"))); // NOI18N
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 80, 100));

        jButton5.setBackground(new java.awt.Color(0, 37, 37));
        jButton5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Back");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 80, 100));

        lblc.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        lblc.setForeground(new java.awt.Color(0, 255, 51));
        lblc.setText("Date");
        jPanel5.add(lblc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, -1));

        lblc1.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        lblc1.setForeground(new java.awt.Color(0, 255, 51));
        lblc1.setText("Clock");
        jPanel5.add(lblc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, -1, -1));

        jLabel30.setBackground(new java.awt.Color(0, 255, 153));
        jLabel30.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 255, 153));
        jLabel30.setText("Time :");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        jLabel24.setBackground(new java.awt.Color(0, 255, 153));
        jLabel24.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 255, 153));
        jLabel24.setText("Date :");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 300, 610));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("ID :");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        jTextField19.setEditable(false);
        jTextField19.setBackground(new java.awt.Color(0, 51, 51));
        jTextField19.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField19.setForeground(new java.awt.Color(255, 255, 255));
        jTextField19.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField19.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField19KeyTyped(evt);
            }
        });
        jPanel3.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 150, 40));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(0, 51, 51));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 150, 40));

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(0, 51, 51));
        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(255, 255, 255));
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField11jTextField7KeyTyped(evt);
            }
        });
        jPanel3.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 150, 40));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Insentives :");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, -1, -1));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(0, 51, 51));
        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });
        jPanel3.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 150, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contact :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Job Reference :");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Firstname :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(0, 51, 51));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 150, 40));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(0, 51, 51));
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 150, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Surname :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address :");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(0, 51, 51));
        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 150, 40));

        jTextField18.setEditable(false);
        jTextField18.setBackground(new java.awt.Color(0, 51, 51));
        jTextField18.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField18.setForeground(new java.awt.Color(255, 255, 255));
        jTextField18.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 150, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Gender :");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Over Time :");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(0, 51, 51));
        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 255, 255));
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField10jTextField7KeyTyped(evt);
            }
        });
        jPanel3.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 150, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Net Pay :");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, -1, -1));

        jTextField15.setEditable(false);
        jTextField15.setBackground(new java.awt.Color(0, 51, 51));
        jTextField15.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(255, 255, 255));
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField15jTextField7KeyTyped(evt);
            }
        });
        jPanel3.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 150, 40));

        jTextField14.setEditable(false);
        jTextField14.setBackground(new java.awt.Color(0, 51, 51));
        jTextField14.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(255, 255, 255));
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField14jTextField7KeyTyped(evt);
            }
        });
        jPanel3.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 150, 40));

        jTextField13.setEditable(false);
        jTextField13.setBackground(new java.awt.Color(0, 51, 51));
        jTextField13.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(255, 255, 255));
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField13jTextField7KeyTyped(evt);
            }
        });
        jPanel3.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, 150, 40));

        jTextField12.setEditable(false);
        jTextField12.setBackground(new java.awt.Color(0, 51, 51));
        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(255, 255, 255));
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField12jTextField7KeyTyped(evt);
            }
        });
        jPanel3.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 150, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Student Loan :");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Tax :");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Gross Pay :");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, -1, -1));

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(0, 51, 51));
        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField9jTextField7KeyTyped(evt);
            }
        });
        jPanel3.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 150, 40));

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(0, 51, 51));
        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField8jTextField7KeyTyped(evt);
            }
        });
        jPanel3.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 150, 40));

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(0, 51, 51));
        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField7KeyTyped(evt);
            }
        });
        jPanel3.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 150, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Hour Worked :");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 110, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Payroll no :");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/employee.png"))); // NOI18N
        jLabel26.setText("jLabel26");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 70, 60));

        jTextField17.setEditable(false);
        jTextField17.setBackground(new java.awt.Color(51, 51, 51));
        jTextField17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField17.setForeground(new java.awt.Color(255, 255, 255));
        jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField17.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Total Of Workers", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jTextField17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 180, 80));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Basic Pay :");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 90, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Basic Pay :");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 90, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 920, 340));

        jPanel6.setBackground(new java.awt.Color(0, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Footlight MT Light", 1, 45)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CashSEA");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 180, 40));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo.png"))); // NOI18N
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 90, 70));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 340, 110));

        jPanel12.setBackground(new java.awt.Color(0, 51, 51));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Footlight MT Light", 1, 48)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText(" Sea Find Ways....");
        jLabel36.setToolTipText("");
        jPanel12.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 530, 50));
        jPanel12.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 90, 80));
        jPanel12.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 50, 40));
        jPanel12.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 80, 30));
        jPanel12.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, 50, 50));
        jPanel12.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 60, 50));
        jPanel12.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 40, 50));
        jPanel12.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 240, 100));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 640, 920, 110));

        jPanel7.setBackground(new java.awt.Color(0, 26, 26));
        jPanel7.setForeground(new java.awt.Color(0, 37, 37));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel7MousePressed(evt);
            }
        });
        jPanel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel7MouseDragged(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1220, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 750));

        setSize(new java.awt.Dimension(1220, 749));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        fecth();
        count();
}//GEN-LAST:event_formWindowOpened

private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
 try{ 
               int row =jTable1.getSelectedRow();
               String tc=(jTable1.getModel().getValueAt(row, 0).toString());
               String sql = "select * from APP.CASHC where ID="+tc+"";
               mystateObj=myconObj.prepareStatement(sql);
               myresObj=mystateObj.executeQuery();
               
              if(myresObj.next()){
       String tid = myresObj.getString("ID");
      jTextField19.setText(tid);           
       String Jr = myresObj.getString("JOB_REFERENCE");
      jTextField2.setText(Jr);
       String fn = myresObj.getString("FIRSTNAME");
      jTextField3.setText(fn);      
       String sn = myresObj.getString("SURNAME");
      jTextField4.setText(sn);     
       String ad = myresObj.getString("ADDRESS");
      jTextField5.setText(ad);            
       String hw = myresObj.getString("HOUR_WORK");
      jTextField7.setText(hw);      
       String bp = myresObj.getString("BASIC_PAY");
      jTextField8.setText(bp);     
       String prn = myresObj.getString("PAYROLL_NUM");
      jTextField9.setText(prn);     
      String ot = myresObj.getString("OVERTIME_RATE");
      jTextField10.setText(ot);     
       String ni = myresObj.getString("NATIONAL_IN");
      jTextField11.setText(ni);     
       String sl = myresObj.getString("STUDENT_LOAN");
      jTextField12.setText(sl);    
       String tax = myresObj.getString("TAX");
      jTextField13.setText(tax);    
       String gp = myresObj.getString("GROSS_PAY");
      jTextField14.setText(gp);   
       String np = myresObj.getString("NET_PAY");
      jTextField15.setText(np);    
       String g = myresObj.getString("GENDER");
      jTextField18.setText(g);
       String pn = myresObj.getString("CONTACT_NUM");
      jTextField6.setText(pn);
     }
           }
           catch (Exception e){
        JOptionPane.showMessageDialog(null, e);
    }      
}//GEN-LAST:event_jTable1MouseClicked

private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
     
}//GEN-LAST:event_jTable1KeyPressed

private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_UP || evt.getKeyCode()==KeyEvent.VK_DOWN ){
           
           try{ 
               int row =jTable1.getSelectedRow();
               String tc=(jTable1.getModel().getValueAt(row, 0).toString());
               String sql = "select * from APP.CASHC where ID="+tc+"";
               mystateObj=myconObj.prepareStatement(sql);
               myresObj=mystateObj.executeQuery();
               
              if(myresObj.next()){
       String tid = myresObj.getString("ID");
      jTextField19.setText(tid);           
       String Jr = myresObj.getString("JOB_REFERENCE");
      jTextField2.setText(Jr);
       String fn = myresObj.getString("FIRSTNAME");
      jTextField3.setText(fn);      
       String sn = myresObj.getString("SURNAME");
      jTextField4.setText(sn);     
       String ad = myresObj.getString("ADDRESS");
      jTextField5.setText(ad);           
       String hw = myresObj.getString("HOUR_WORK");
      jTextField7.setText(hw);      
       String bp = myresObj.getString("BASIC_PAY");
      jTextField8.setText(bp);     
       String prn = myresObj.getString("PAYROLL_NUM");
      jTextField9.setText(prn);     
      String ot = myresObj.getString("OVERTIME_RATE");
      jTextField10.setText(ot);     
       String ni = myresObj.getString("NATIONAL_IN");
      jTextField11.setText(ni);     
       String sl = myresObj.getString("STUDENT_LOAN");
      jTextField12.setText(sl);    
       String tax = myresObj.getString("TAX");
      jTextField13.setText(tax);    
       String gp = myresObj.getString("GROSS_PAY");
      jTextField14.setText(gp);   
       String np = myresObj.getString("NET_PAY");
      jTextField15.setText(np);    
       String g = myresObj.getString("GENDER");
      jTextField18.setText(g);
       String pn = myresObj.getString("CONTACT_NUM");
      jTextField6.setText(pn);
     }
           }
           catch (Exception e){
        JOptionPane.showMessageDialog(null, e);
    }      
           
       }
}//GEN-LAST:event_jTable1KeyReleased

private void jTextField16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField16MouseClicked
    
}//GEN-LAST:event_jTextField16MouseClicked

private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
       
}//GEN-LAST:event_jTextField16ActionPerformed

private void jTextField16KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField16KeyPressed
     
}//GEN-LAST:event_jTextField16KeyPressed

private void jTextField16KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField16KeyReleased

        try{
   myconObj = DriverManager.getConnection("jdbc:derby://localhost:1527/Payrol","tian","tian");
        String sql = "select * from APP.CASHC where FIRSTNAME=? or SURNAME=?";
     mystateObj   = myconObj.prepareStatement(sql);
     mystateObj.setString(1,jTextField16.getText());
     mystateObj.setString(2,jTextField16.getText());
    myresObj=mystateObj.executeQuery();
     
     if(myresObj.next()){
          String tid = myresObj.getString("ID");
      jTextField19.setText(tid);
         
      String Jr = myresObj.getString("JOB_REFERENCE");
      jTextField2.setText(Jr);
      
       String fn = myresObj.getString("FIRSTNAME");
      jTextField3.setText(fn);
      
       String sn = myresObj.getString("SURNAME");
      jTextField4.setText(sn);
      
       String ad = myresObj.getString("ADDRESS");
      jTextField5.setText(ad);
          
      
       String hw = myresObj.getString("HOUR_WORK");
      jTextField7.setText(hw);
      
       String bp = myresObj.getString("BASIC_PAY");
      jTextField8.setText(bp);
      
       String prn = myresObj.getString("PAYROLL_NUM");
      jTextField9.setText(prn);
      
       String ot = myresObj.getString("OVERTIME_RATE");
      jTextField10.setText(ot);
      
       String ni = myresObj.getString("NATIONAL_IN");
      jTextField11.setText(ni);
      
       String sl = myresObj.getString("STUDENT_LOAN");
      jTextField12.setText(sl);
      
       String tax = myresObj.getString("TAX");
      jTextField13.setText(tax);
      
       String gp = myresObj.getString("GROSS_PAY");
      jTextField14.setText(gp); 
      
       String np = myresObj.getString("NET_PAY");
      jTextField15.setText(np);
      
       String g = myresObj.getString("GENDER");
      jTextField18.setText(g);
      
       String pn = myresObj.getString("CONTACT_NUM");
      jTextField6.setText(pn);
     }
    
    } 
    catch (SQLException e){
        JOptionPane.showMessageDialog(null, e);
    }      
        
        
        
             
              
            
}//GEN-LAST:event_jTextField16KeyReleased

private void jTextField16KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField16KeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField16KeyTyped

private void jTextField20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField20MouseClicked
       
}//GEN-LAST:event_jTextField20MouseClicked

private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField20ActionPerformed

private void jTextField20KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField20KeyPressed

}//GEN-LAST:event_jTextField20KeyPressed

private void jTextField20KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField20KeyReleased
int w = Integer.parseInt(jTextField20.getText());
String R = Integer.toString(w);
        
        try{
   myconObj = DriverManager.getConnection("jdbc:derby://localhost:1527/Payrol","tian","tian");
        String sql = "select * from APP.CASHC where ID=?";
     mystateObj   = myconObj.prepareStatement(sql);
     mystateObj.setString(1,R);
    myresObj=mystateObj.executeQuery();
     
     if(myresObj.next()){
          String tid = myresObj.getString("ID");
      jTextField19.setText(tid);
         
      String Jr = myresObj.getString("JOB_REFERENCE");
      jTextField2.setText(Jr);
      
       String fn = myresObj.getString("FIRSTNAME");
      jTextField3.setText(fn);
      
       String sn = myresObj.getString("SURNAME");
      jTextField4.setText(sn);
      
       String ad = myresObj.getString("ADDRESS");
      jTextField5.setText(ad);
      
      
       String pn = myresObj.getString("CONTACT_NUM");
      jTextField6.setText(pn);
      
       String hw = myresObj.getString("HOUR_WORK");
      jTextField7.setText(hw);
      
       String bp = myresObj.getString("BASIC_PAY");
      jTextField8.setText(bp);
      
       String prn = myresObj.getString("PAYROLL_NUM");
      jTextField9.setText(prn);
      
       String ot = myresObj.getString("OVERTIME_RATE");
      jTextField10.setText(ot);
      
       String ni = myresObj.getString("NATIONAL_IN");
      jTextField11.setText(ni);
      
       String sl = myresObj.getString("STUDENT_LOAN");
      jTextField12.setText(sl);
      
       String tax = myresObj.getString("TAX");
      jTextField13.setText(tax);
      
       String gp = myresObj.getString("GROSS_PAY");
      jTextField14.setText(gp); 
      
       String np = myresObj.getString("NET_PAY");
      jTextField15.setText(np);
      
       String g = myresObj.getString("GENDER");
      jTextField18.setText(g);
     }
    
    } 
    catch (SQLException e){
        JOptionPane.showMessageDialog(null, e);
    }       
}//GEN-LAST:event_jTextField20KeyReleased

private void jTextField20KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField20KeyTyped
   char c=evt.getKeyChar();
        if(Character.isLetter(c)&&!evt.isAltDown()){
            getToolkit().beep();
            JOptionPane.showConfirmDialog(null,"Numbers Only!!!","Numbers Only Error", JOptionPane.DEFAULT_OPTION);
            evt.consume();
          }
}//GEN-LAST:event_jTextField20KeyTyped

private void jTextField19KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField19KeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField19KeyTyped

private void jTextField11jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11jTextField7KeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField11jTextField7KeyTyped

private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField6KeyTyped

private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased

}//GEN-LAST:event_jTextField3KeyReleased

private void jTextField10jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10jTextField7KeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField10jTextField7KeyTyped

private void jTextField15jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField15jTextField7KeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField15jTextField7KeyTyped

private void jTextField14jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14jTextField7KeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField14jTextField7KeyTyped

private void jTextField13jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField13jTextField7KeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField13jTextField7KeyTyped

private void jTextField12jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12jTextField7KeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField12jTextField7KeyTyped

private void jTextField9jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9jTextField7KeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField9jTextField7KeyTyped

private void jTextField8jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8jTextField7KeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField8jTextField7KeyTyped

private void jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField7KeyTyped

private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField17ActionPerformed

private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
      int YesOrNo = JOptionPane.showConfirmDialog(null,"Are sure you want to Exit","Exit", JOptionPane.YES_NO_OPTION);
             if(YesOrNo == 0)
        {
          System.exit(0);
        }
       
}//GEN-LAST:event_jLabel34MouseClicked

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   jTextField2.setText(null);
                    jTextField3.setText(null);
                    jTextField4.setText(null);
                            jTextField5.setText(null);
                            jTextField6.setText(null);
                                    jTextField7.setText(null);
                                    jTextField8.setText(null);
                                            jTextField9.setText(null);
                                            jTextField10.setText(null);
                                                    jTextField11.setText(null);
                                                    jTextField12.setText(null);
                                                            jTextField13.setText(null);
                                                            jTextField14.setText(null);
                                                                    jTextField15.setText(null);
                                                                    jTextField19.setText(null);
                                                                    jTextField18.setText(null);
                                                                    jTextField16.setText(null);
                                                                    jTextField20.setText(null);
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   int YesOrNo = JOptionPane.showConfirmDialog(null,"Are you Sure you want to Delete Data","Delete All Data", JOptionPane.YES_NO_OPTION);
        if(YesOrNo == 0){
        try{
            myconObj = DriverManager.getConnection("jdbc:derby://localhost:1527/Payrol","tian","tian");
            int id = Integer.parseInt(jTextField20.getText());  
            String G = jTextField16.getText();
            String sql = "delete from APP.CASHC where FIRSTNAME =? or SURNAME =? or ID =? ";
            PreparedStatement preparedStatement = myconObj.prepareStatement(sql);      
            preparedStatement.setString(1,G);  
            preparedStatement.setString(2,G); 
             preparedStatement.setInt(3,id); 
            preparedStatement.execute();
            JOptionPane.showMessageDialog(null,"Data Have been delete","Data File",JOptionPane.INFORMATION_MESSAGE);
            fecth();
            count();
            jTextField20.setText(null);
            jTextField19.setText(null);
            jTextField16.setText(null);
            jTextField15.setText(null);
            jTextField14.setText(null);
            jTextField13.setText(null);
            jTextField12.setText(null);
            jTextField11.setText(null);
            jTextField10.setText(null);
            jTextField9.setText(null);
            jTextField8.setText(null);
            jTextField7.setText(null);
            jTextField6.setText(null);
            jTextField5.setText(null);
            jTextField4.setText(null);
            jTextField3.setText(null);
            jTextField2.setText(null);
            jTextField18.setText(null);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
        
        
        }
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    try{
            jTable1.print();

        }
        catch(Exception e){
            Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null,e);
        }
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     basebody l = new basebody();
        int YesOrNo = JOptionPane.showConfirmDialog(null,"Return to Main Form","Return", JOptionPane.YES_NO_OPTION);
             if(YesOrNo == 0)
        {
             l.show();
        this.hide();
        }
}//GEN-LAST:event_jButton5ActionPerformed

private void jPanel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MousePressed
    mousepX=evt.getX();
    mousepY=evt.getY();
}//GEN-LAST:event_jPanel7MousePressed

private void jPanel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseDragged
    int cordX=evt.getXOnScreen();
    int cordY=evt.getYOnScreen();

    this.setLocation(cordX-mousepX, cordY-mousepY);
}//GEN-LAST:event_jPanel7MouseDragged


public void show_Users_In_Jtable(){
  
    
}
       public void fecth(){
    try{
        
         myconObj = DriverManager.getConnection("jdbc:derby://localhost:1527/Payrol","tian","tian");
        String sql = "select * from APP.CASHC order by ID";
        mystateObj  = myconObj.prepareStatement(sql);
        myresObj=mystateObj.executeQuery();
    
         jTable1.setModel(DbUtils.resultSetToTableModel(myresObj));
    
      
        
    }
    catch(Exception e){
 
        JOptionPane.showMessageDialog(null,e);
    }
}
     public void count(){
         try{
              myconObj = DriverManager.getConnection("jdbc:derby://localhost:1527/Payrol","tian","tian");
                 String sql = "Select count(ID)from APP.CASHC";
        mystateObj  = myconObj.prepareStatement(sql);
        myresObj=mystateObj.executeQuery();
        if(myresObj.next())
        {
            String sum = myresObj.getString(1);
            jTextField17.setText(sum);
        }
        
         }
        catch(Exception e){
 
        JOptionPane.showMessageDialog(null,e);
    }
     }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Search().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblc;
    private javax.swing.JLabel lblc1;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("pay.png")));
    }
    public void Dates(){
       
 Thread clock = new Thread(){
            @Override
    public void run(){
     for(;;)   {
      
    try{
           Calendar d = new GregorianCalendar();
    int month = d.get(Calendar.MONTH);
    int year = d.get(Calendar.YEAR);
    int day = d.get(Calendar.DAY_OF_MONTH);
    lblc.setText((month+1)+"/"+day+"/"+year);
    
   int sec = d.get(Calendar.SECOND);
   String ssec;
   if(sec<10)ssec = "0" + sec;
    else ssec = ""+sec;
    int min = d.get(Calendar.MINUTE);
    String fmin;
    if(min<10)fmin = "0" + min;
    else fmin = ""+min;
    int hour = d.get(Calendar.HOUR);
    int ampm = d.get(Calendar.AM_PM);
    String stampm;
    if (ampm ==0 ) stampm="AM";
    else stampm="PM";
    lblc1.setText(hour+":"+(fmin)+":"+ssec+" "+stampm);
      sleep(1000);
    }
    catch(Exception e){
        
    }
    }
    }
};
        clock.start();
    }



}

